### ISSUE TITLE
Update README to include npm install

### ISSUE THREAD

**Issue by dfols** [REVENGE977/stremio-enhanced-community#15]
The current build instructions do not include an initial npm install step. As a result, most users will encounter errors due to missing packages, such as tsc, when attempting to run the build commands.

	1.	Clone the repository.
	2.	Follow the README instructions and try to run the build command.
	3.	See error due to missing packages, such as tsc.

Expected behavior
The build should succeed without errors if all necessary dependencies are installed.

Suggested Fix
To ensure users have the required packages, please include an initial npm install command before the run steps in the documentation for building the project locally.

**Comment by REVENGE977** [comment]
done
